"""Seed investment_rules and signal_knowledge tables with initial data.

Run: python -m app.db.seed_brain
"""

from app.db.supabase import get_client
from loguru import logger


INVESTMENT_RULES = [
    # ═══ SOLVENCY BLOCKERS ═══
    {
        "name": "minimum_market_cap",
        "rule_type": "SOLVENCY",
        "bucket": "BOTH",
        "description": "Market cap must exceed $50M to avoid penny stock manipulation and thin liquidity. Stocks below this threshold are excluded from analysis.",
        "formula": "market_cap > 50000000",
        "threshold_min": 50000000,
        "threshold_unit": "absolute",
        "is_blocker": True,
        "weight_safe": 0,
        "weight_risk": 0,
        "source_name": "SEC / Investopedia",
        "source_url": "https://www.investopedia.com/terms/p/pennystock.asp",
    },
    {
        "name": "minimum_daily_volume",
        "rule_type": "SOLVENCY",
        "bucket": "BOTH",
        "description": "Average daily volume must exceed 200K shares for screening, 50K for analysis. Low volume means wide spreads and difficulty exiting positions.",
        "formula": "avg_volume >= 200000 (screening) AND avg_volume >= 50000 (analysis)",
        "threshold_min": 200000,
        "threshold_unit": "absolute",
        "is_blocker": True,
        "weight_safe": 0,
        "weight_risk": 0,
        "source_name": "Signa Backtest",
        "source_url": None,
    },
    {
        "name": "rsi_overbought_blocker",
        "rule_type": "SOLVENCY",
        "bucket": "BOTH",
        "description": "RSI above 75 indicates overbought conditions with 60%+ fail rate. Auto-blocks BUY signals regardless of other factors.",
        "formula": "rsi <= 75",
        "threshold_max": 75,
        "threshold_unit": "absolute",
        "is_blocker": True,
        "weight_safe": 0,
        "weight_risk": 0,
        "source_name": "Signa Backtest (Oct 2024 - Apr 2025)",
        "source_url": None,
        "notes": "Backtest confirmed: RSI > 75 has 60%+ fail rate across 30 tickers over 6 months.",
    },
    {
        "name": "hostile_macro_blocker",
        "rule_type": "SOLVENCY",
        "bucket": "BOTH",
        "description": "When macro environment is classified as hostile (rising rates + high inflation + elevated VIX), block new BUY signals.",
        "formula": "macro_environment != 'hostile'",
        "threshold_unit": "category",
        "is_blocker": True,
        "weight_safe": 0,
        "weight_risk": 0,
        "source_name": "FRED / Federal Reserve",
        "source_url": "https://fred.stlouisfed.org/",
    },
    {
        "name": "fraud_red_flag_blocker",
        "rule_type": "SOLVENCY",
        "bucket": "BOTH",
        "description": "Auto-block if sentiment data contains fraud-related keywords: fraud, SEC investigation, lawsuit, scam, ponzi, insider trading.",
        "formula": "NOT any(keyword in sentiment for keyword in fraud_keywords)",
        "threshold_unit": "keywords",
        "is_blocker": True,
        "weight_safe": 0,
        "weight_risk": 0,
        "source_name": "SEC Enforcement",
        "source_url": "https://www.sec.gov/enforcement",
    },
    {
        "name": "minimum_price",
        "rule_type": "SOLVENCY",
        "bucket": "BOTH",
        "description": "Stock price must be above $1.00 to avoid sub-penny stocks and potential delistings.",
        "formula": "price >= 1.0",
        "threshold_min": 1.0,
        "threshold_unit": "absolute",
        "is_blocker": True,
        "weight_safe": 0,
        "weight_risk": 0,
        "source_name": "NYSE/NASDAQ Listing Requirements",
        "source_url": None,
    },

    # ═══ TECHNICAL RULES ═══
    {
        "name": "rsi_sweet_spot",
        "rule_type": "TECHNICAL",
        "bucket": "BOTH",
        "description": "RSI between 50-65 is the optimal entry zone. Backtest validated: this range has the highest win rate across both Safe Income and High Risk buckets.",
        "formula": "50 <= rsi <= 65 → +15 points",
        "threshold_min": 50,
        "threshold_max": 65,
        "threshold_unit": "absolute",
        "is_blocker": False,
        "weight_safe": 0.05,
        "weight_risk": 0.10,
        "source_name": "Signa Backtest (6-month validation)",
        "source_url": None,
        "notes": "RSI 50-65 outperformed all other RSI ranges in backtest. Oversold (<30) is NOT better — falling knife risk.",
    },
    {
        "name": "macd_surger",
        "rule_type": "TECHNICAL",
        "bucket": "HIGH_RISK",
        "description": "MACD histogram > 2.0 predicts momentum surges. Backtest showed 3.3x average return vs 1.5x on normal signals.",
        "formula": "macd_histogram > 2.0 → +15 points",
        "threshold_min": 2.0,
        "threshold_unit": "absolute",
        "is_blocker": False,
        "weight_safe": 0.03,
        "weight_risk": 0.08,
        "source_name": "Signa Backtest",
        "source_url": None,
    },
    {
        "name": "golden_death_cross",
        "rule_type": "TECHNICAL",
        "bucket": "BOTH",
        "description": "SMA 50 crossing above SMA 200 (golden cross) adds +12 points. Death cross subtracts 12 points.",
        "formula": "golden_cross → +12, death_cross → -12",
        "threshold_unit": "event",
        "is_blocker": False,
        "weight_safe": 0.05,
        "weight_risk": 0.05,
        "source_name": "Technical Analysis of Financial Markets (Murphy)",
        "source_url": None,
    },
    {
        "name": "volume_confirmation",
        "rule_type": "TECHNICAL",
        "bucket": "BOTH",
        "description": "Volume z-score confirms price moves. Z-score 1.0-2.0 adds 8 points (healthy volume). Above 2.0 adds 5 (possibly climactic). Below -1.0 subtracts 8 (no conviction).",
        "formula": "1.0 < volume_zscore <= 2.0 → +8; volume_zscore > 2.0 → +5; volume_zscore < -1.0 → -8",
        "threshold_min": 1.0,
        "threshold_max": 2.0,
        "threshold_unit": "z-score",
        "is_blocker": False,
        "weight_safe": 0.03,
        "weight_risk": 0.05,
        "source_name": "Volume Price Analysis (Coulling)",
        "source_url": None,
    },
    {
        "name": "momentum_trap",
        "rule_type": "TECHNICAL",
        "bucket": "HIGH_RISK",
        "description": "Momentum above 5% is a trap with only 46.2% win rate. Sweet spot is +1% to +3%.",
        "formula": "momentum > 5% → penalty; 1% <= momentum <= 3% → bonus",
        "threshold_min": 1,
        "threshold_max": 3,
        "threshold_unit": "percent",
        "is_blocker": False,
        "weight_safe": 0,
        "weight_risk": 0.05,
        "source_name": "Signa Backtest",
        "source_url": None,
        "notes": "Backtest finding: momentum > 5% had 46.2% win rate vs 58% for 1-3% range.",
    },

    # ═══ FUNDAMENTAL RULES ═══
    {
        "name": "dividend_yield_scoring",
        "rule_type": "FUNDAMENTAL",
        "bucket": "SAFE_INCOME",
        "description": "Dividend yield drives Safe Income scoring. >5% yield adds 25 points, 3-5% adds 15, 1-3% adds 5, zero yield subtracts 30.",
        "formula": "yield > 0.05 → +25; yield > 0.03 → +15; yield > 0.01 → +5; yield == 0 → -30",
        "threshold_min": 0.01,
        "threshold_unit": "percent",
        "is_blocker": False,
        "weight_safe": 0.35,
        "weight_risk": 0,
        "source_name": "Canadian Dividend Investor",
        "source_url": None,
    },
    {
        "name": "payout_ratio_health",
        "rule_type": "FUNDAMENTAL",
        "bucket": "SAFE_INCOME",
        "description": "Healthy payout ratio (30-60%) adds 15 points. Above 85% subtracts 15 (dividend at risk).",
        "formula": "0.30 <= payout_ratio <= 0.60 → +15; payout_ratio > 0.85 → -15",
        "threshold_min": 0.30,
        "threshold_max": 0.60,
        "threshold_unit": "ratio",
        "is_blocker": False,
        "weight_safe": 0.10,
        "weight_risk": 0,
        "source_name": "Dividend Safety Analysis",
        "source_url": None,
    },
    {
        "name": "eps_growth_scoring",
        "rule_type": "FUNDAMENTAL",
        "bucket": "HIGH_RISK",
        "description": "EPS growth drives High Risk fundamental score. >25% growth adds 20 points, >10% adds 10, negative growth subtracts 10.",
        "formula": "eps_growth > 0.25 → +20; eps_growth > 0.10 → +10; eps_growth < 0 → -10",
        "threshold_min": 0.10,
        "threshold_unit": "percent",
        "is_blocker": False,
        "weight_safe": 0,
        "weight_risk": 0.05,
        "source_name": "Growth Investing Fundamentals",
        "source_url": None,
    },
    {
        "name": "debt_to_equity",
        "rule_type": "FUNDAMENTAL",
        "bucket": "SAFE_INCOME",
        "description": "Low debt-to-equity (<50) adds 10 points for Safe Income. High D/E (>150) subtracts 10.",
        "formula": "debt_to_equity < 50 → +10; debt_to_equity > 150 → -10",
        "threshold_max": 50,
        "threshold_unit": "ratio",
        "is_blocker": False,
        "weight_safe": 0.08,
        "weight_risk": 0,
        "source_name": "Benjamin Graham / Value Investing",
        "source_url": None,
    },

    # ═══ CATALYST RULES ═══
    {
        "name": "near_term_catalyst",
        "rule_type": "CATALYST",
        "bucket": "HIGH_RISK",
        "description": "A confirmed catalyst within 30 days (earnings, product launch, FDA approval) adds 30 points. Within 90 days adds 15. No catalyst returns only 30 base.",
        "formula": "catalyst_date within 30d → +30; within 90d → +15; no catalyst → base 30",
        "threshold_min": 0,
        "threshold_max": 30,
        "threshold_unit": "days",
        "is_blocker": False,
        "weight_safe": 0.05,
        "weight_risk": 0.30,
        "source_name": "Event-Driven Trading",
        "source_url": None,
    },
    {
        "name": "earnings_catalyst",
        "rule_type": "CATALYST",
        "bucket": "BOTH",
        "description": "Upcoming earnings within 14 days increases catalyst score. Earnings beats historically create 3-5% moves.",
        "formula": "earnings_date within 14d → catalyst boost",
        "threshold_max": 14,
        "threshold_unit": "days",
        "is_blocker": False,
        "weight_safe": 0.05,
        "weight_risk": 0.10,
        "source_name": "Earnings Whisper / Market Beat",
        "source_url": None,
    },

    # ═══ SELL RULES ═══
    {
        "name": "score_below_hold",
        "rule_type": "SELL",
        "bucket": "BOTH",
        "description": "Score drops below 50 (HOLD threshold) → signal changes to AVOID. This is the primary sell trigger.",
        "formula": "score < 50 → action = AVOID",
        "threshold_max": 50,
        "threshold_unit": "absolute",
        "is_blocker": False,
        "weight_safe": 0,
        "weight_risk": 0,
        "source_name": "Signa Scoring Engine",
        "source_url": None,
    },
    {
        "name": "score_ceiling_overbought",
        "rule_type": "SELL",
        "bucket": "BOTH",
        "description": "Score above 90 triggers HOLD instead of BUY. Overbought trap — backtest showed inverted win rates above score 72.",
        "formula": "score > 90 → action = HOLD (overbought ceiling)",
        "threshold_min": 90,
        "threshold_unit": "absolute",
        "is_blocker": False,
        "weight_safe": 0,
        "weight_risk": 0,
        "source_name": "Signa Backtest",
        "source_url": None,
        "notes": "Scores above 72 have inverted win rates in backtest. 90+ ceiling prevents false conviction.",
    },
    {
        "name": "score_drop_weakening",
        "rule_type": "SELL",
        "bucket": "BOTH",
        "description": "Score drops 15+ points from previous scan → status changes to WEAKENING. Signals deteriorating conditions.",
        "formula": "current_score < prev_score - 15 → status = WEAKENING",
        "threshold_min": 15,
        "threshold_unit": "points_drop",
        "is_blocker": False,
        "weight_safe": 0,
        "weight_risk": 0,
        "source_name": "Signa Signal Engine",
        "source_url": None,
    },
    {
        "name": "action_reversal_cancelled",
        "rule_type": "SELL",
        "bucket": "BOTH",
        "description": "If previous signal was BUY and current is SELL or AVOID → status = CANCELLED. Urgent signal reversal.",
        "formula": "prev_action == BUY AND current_action in (SELL, AVOID) → status = CANCELLED",
        "threshold_unit": "event",
        "is_blocker": False,
        "weight_safe": 0,
        "weight_risk": 0,
        "source_name": "Signa Signal Engine",
        "source_url": None,
    },
    {
        "name": "stop_loss_hit",
        "rule_type": "SELL",
        "bucket": "BOTH",
        "description": "When current price drops below the signal's stop loss level, auto-close position and send Telegram alert.",
        "formula": "current_price < stop_loss → auto_close + alert",
        "threshold_unit": "price",
        "is_blocker": False,
        "weight_safe": 0,
        "weight_risk": 0,
        "source_name": "Risk Management Best Practice",
        "source_url": None,
    },
    {
        "name": "target_reached",
        "rule_type": "SELL",
        "bucket": "BOTH",
        "description": "When current price reaches or exceeds the signal's target price, send Telegram alert to consider taking profits.",
        "formula": "current_price >= target_price → alert",
        "threshold_unit": "price",
        "is_blocker": False,
        "weight_safe": 0,
        "weight_risk": 0,
        "source_name": "Risk Management Best Practice",
        "source_url": None,
    },
    {
        "name": "pnl_milestone_alert",
        "rule_type": "SELL",
        "bucket": "BOTH",
        "description": "Alert when position crosses +5% or -5% P&L milestone. Helps track position performance.",
        "formula": "abs(pnl_pct) >= 5.0 → alert",
        "threshold_min": 5.0,
        "threshold_max": -5.0,
        "threshold_unit": "percent",
        "is_blocker": False,
        "weight_safe": 0,
        "weight_risk": 0,
        "source_name": "Signa Position Monitor",
        "source_url": None,
    },

    # ═══ KELLY CRITERION ═══
    {
        "name": "kelly_position_sizing",
        "rule_type": "KELLY",
        "bucket": "BOTH",
        "description": "Kelly Criterion calculates optimal position size based on win rate, risk/reward ratio, and signal score. Uses fractional Kelly (0.25x) for safety. Max position capped at 15% of portfolio.",
        "formula": "kelly_pct = (win_rate * rr - (1 - win_rate)) / rr * 0.25; capped at 0.15",
        "threshold_max": 0.15,
        "threshold_unit": "percent_of_portfolio",
        "is_blocker": False,
        "weight_safe": 0,
        "weight_risk": 0,
        "source_name": "Kelly Criterion (J.L. Kelly Jr., 1956)",
        "source_url": "https://en.wikipedia.org/wiki/Kelly_criterion",
        "notes": "Using fractional Kelly (25%) to reduce variance. Backtest-validated score-to-win-rate mapping.",
    },

    # ═══ NEW: MARKET REGIME + MOMENTUM + CANADA TAX ═══
    {
        "name": "market_regime_vix_crisis_blocker",
        "rule_type": "SOLVENCY",
        "bucket": "HIGH_RISK",
        "description": "Block ALL High Risk signals when VIX exceeds 30. Momentum strategies crash in panic states. Hard market-wide blocker checked once per day before the ticker loop starts.",
        "formula": "macro_data_vix < 30",
        "threshold_max": 30,
        "threshold_unit": "absolute",
        "is_blocker": True,
        "weight_safe": 0,
        "weight_risk": 0,
        "source_name": "Morningstar - Momentum Has Its Moments",
        "source_url": "https://www.morningstar.com/markets/achilles-heel-momentum-strategies",
    },
    {
        "name": "minimum_daily_dollar_volume",
        "rule_type": "SOLVENCY",
        "bucket": "BOTH",
        "description": "Minimum average daily dollar volume of $500,000 to ensure liquidity for entry and exit. Below this level bid-ask spreads and slippage eat into any signal advantage.",
        "formula": "avg_daily_dollar_volume > 500000",
        "threshold_min": 500000,
        "threshold_unit": "absolute",
        "is_blocker": True,
        "weight_safe": 0,
        "weight_risk": 0,
        "source_name": "Medhat and Schmeling Short-Term Momentum 2022",
        "source_url": "https://www.morningstar.com/markets/achilles-heel-momentum-strategies",
    },
    {
        "name": "high_volume_momentum_continuation_boost",
        "rule_type": "CATALYST",
        "bucket": "HIGH_RISK",
        "description": "For stocks with average daily dollar volume above $1M, short-term momentum is expected to CONTINUE not reverse. Score boost when liquid stock shows upward momentum.",
        "formula": "avg_daily_dollar_volume > 1000000 AND momentum_5d > 0",
        "is_blocker": False,
        "weight_safe": 0,
        "weight_risk": 0.08,
        "source_name": "Medhat and Schmeling Short-Term Momentum 2022",
        "source_url": "https://www.morningstar.com/markets/achilles-heel-momentum-strategies",
    },
    {
        "name": "pead_post_earnings_drift_catalyst",
        "rule_type": "CATALYST",
        "bucket": "BOTH",
        "description": "Post-Earnings Announcement Drift. After an earnings BEAT the stock tends to continue rising for 5-10 trading days. Buy AFTER confirmed positive earnings surprise, not before. Mutually exclusive with pre-earnings catalyst.",
        "formula": "eps_surprise > 0.03 AND days_since_earnings <= 3 AND price_change_since_earnings < 0.10",
        "is_blocker": False,
        "weight_safe": 0.15,
        "weight_risk": 0.20,
        "source_name": "Quantpedia PEAD Anomaly",
        "source_url": "https://quantpedia.com/strategies/momentum-factor-effect-in-stocks",
    },
    {
        "name": "superficial_loss_warning_canada",
        "rule_type": "SELL",
        "bucket": "BOTH",
        "description": "Canadian superficial loss rule warning. If same ticker was sold at a loss within last 30 days and a new BUY signal fires, flag to user. Not a hard blocker — show as warning tag.",
        "formula": "days_since_last_sell_at_loss < 30",
        "is_blocker": False,
        "weight_safe": 0,
        "weight_risk": 0,
        "source_name": "TurboTax Canada",
        "source_url": "https://turbotax.intuit.ca/tips/how-to-calculate-capital-gains-when-day-trading-in-canada-6251",
    },
    {
        "name": "rrsp_preferred_for_high_risk",
        "rule_type": "FUNDAMENTAL",
        "bucket": "HIGH_RISK",
        "description": "For HIGH_RISK signals, flag RRSP as preferred account type. CRA explicitly exempts RRSP from business income tax on qualified investment trading. Display as account recommendation on signal card.",
        "formula": "account_recommendation = RRSP",
        "is_blocker": False,
        "weight_safe": 0,
        "weight_risk": 0,
        "source_name": "Investment Executive CRA Folio 10",
        "source_url": "https://www.investmentexecutive.com/inside-track_/jamie-golombek/day-trading-in-a-tfsa-or-rrsp/",
    },
    {
        "name": "tfsa_preferred_for_safe_income",
        "rule_type": "FUNDAMENTAL",
        "bucket": "SAFE_INCOME",
        "description": "For SAFE_INCOME signals, flag TFSA as preferred account type. Dividend income and longer holds are the intended TFSA use under CRA guidelines.",
        "formula": "account_recommendation = TFSA",
        "is_blocker": False,
        "weight_safe": 0,
        "weight_risk": 0,
        "source_name": "CI Global Asset Management TFSA Rules",
        "source_url": "https://www.cifinancial.com/ci-gam/ca/en/expert-insights/articles/tfsas-and-day-trading-risks.html",
    },

    # ═══ CONTRARIAN / SUPPLY-DEMAND RULES ═══
    {
        "name": "supply_deficit_commodity_boost",
        "rule_type": "CATALYST",
        "bucket": "HIGH_RISK",
        "description": "For commodity/resource tickers, when the sector has a documented supply deficit AND production costs exceed market spot price, add a significant score boost. The logic: price MUST eventually rise above production cost or producers shut down, reducing supply further and forcing price up. This is one of the highest-conviction asymmetric setups in commodity markets. Applies to: mining, energy, drilling, PGMs, uranium.",
        "formula": "IF sector_has_supply_deficit AND production_cost > 1.3 * spot_price THEN score_boost = +15",
        "threshold_min": 1.3,
        "threshold_unit": "ratio",
        "is_blocker": False,
        "weight_safe": 0,
        "weight_risk": 0.10,
        "source_name": "Commodity Supply-Demand Economics",
        "source_url": "https://www.investopedia.com/terms/s/supply.asp",
        "notes": "Inspired by deep-value commodity fund strategies with documented 25-30% annual returns over decades.",
    },
    {
        "name": "contrarian_sentiment_override",
        "rule_type": "CATALYST",
        "bucket": "HIGH_RISK",
        "description": "When an entire SECTOR (not individual stock) has extreme negative sentiment BUT fundamental supply-demand dynamics are improving, flip the sentiment penalty to a bonus. Negative consensus in a fundamentally improving sector means the crowd is wrong — this is where the largest asymmetric returns are found. Only triggers when: (1) sector-wide sentiment is below 25, (2) at least 3 tickers in the sector show improving fundamentals, (3) no fraud or solvency red flags exist.",
        "formula": "IF sector_sentiment < 25 AND sector_fundamentals_improving AND no_red_flags THEN sentiment_score = 100 - sentiment_score (flip)",
        "threshold_max": 25,
        "threshold_unit": "sentiment_score",
        "is_blocker": False,
        "weight_safe": 0,
        "weight_risk": 0.08,
        "source_name": "Contrarian Investing Methodology",
        "source_url": "https://www.investopedia.com/terms/c/contrarian.asp",
        "notes": "The highest-return opportunities often look terrible by standard metrics. Extreme negative sentiment + strong supply-demand = asymmetric upside.",
    },
    {
        "name": "ai_sector_bubble_caution",
        "rule_type": "FUNDAMENTAL",
        "bucket": "HIGH_RISK",
        "description": "Apply additional scrutiny to AI/tech sector signals when valuations are extreme. When a sector has: (1) average P/E above 50, (2) majority of companies unprofitable, (3) consensus is overwhelmingly bullish (sentiment > 85), flag as potential bubble risk. Reduce score by 10 points. This is a sector-level caution, not a hard blocker — some AI companies have real earnings. The flag helps avoid hype-driven false BUY signals.",
        "formula": "IF sector == AI_TECH AND avg_pe > 50 AND pct_unprofitable > 0.5 AND sentiment > 85 THEN score_penalty = -10",
        "threshold_min": 50,
        "threshold_unit": "pe_ratio",
        "is_blocker": False,
        "weight_safe": 0,
        "weight_risk": 0.05,
        "source_name": "Market Bubble Research",
        "source_url": "https://www.investopedia.com/terms/b/bubble.asp",
        "notes": "As of 2026, multiple fund managers with 25-30% track records consider AI valuations disconnected from fundamentals.",
    },
    {
        "name": "replacement_cost_floor",
        "rule_type": "FUNDAMENTAL",
        "bucket": "HIGH_RISK",
        "description": "For capital-intensive businesses (offshore drillers, miners, manufacturers), compare market cap to the replacement cost of their physical assets. When market cap is below 50% of asset replacement cost, the stock is likely mispriced — someone could buy the entire company for less than it costs to build the assets from scratch. This creates a natural price floor and attracts acquirers. Score boost of +12 when market_cap < 0.5 * replacement_cost.",
        "formula": "IF market_cap < 0.5 * replacement_cost_of_assets THEN score_boost = +12",
        "threshold_max": 0.5,
        "threshold_unit": "ratio",
        "is_blocker": False,
        "weight_safe": 0.05,
        "weight_risk": 0.08,
        "source_name": "Replacement Cost Valuation",
        "source_url": "https://www.investopedia.com/terms/r/replacementcost.asp",
        "notes": "Especially relevant for offshore drilling rigs, mining equipment, chemical plants. New-build costs are typically 2-5x what distressed assets trade for.",
    },
]

SIGNAL_KNOWLEDGE = [
    {
        "topic": "STRATEGY_SCOPE",
        "key_concept": "signa_is_short_term_only",
        "explanation": "Signa generates signals for 5 to 20 trading day holding periods. It is NOT a long-term buy-and-hold tool. Signals expire and must be re-evaluated at each scan. A BUY signal today may become HOLD or AVOID within days as conditions change. Never treat a Signa signal as a permanent recommendation.",
        "source_name": "Signa Internal",
    },
    {
        "topic": "STRATEGY_SCOPE",
        "key_concept": "two_bucket_model",
        "explanation": "All tickers are classified into exactly one of two buckets: SAFE_INCOME (dividend-paying, stable, low volatility) or HIGH_RISK (growth, momentum, crypto, speculative). Each bucket uses different scoring weights. Safe Income emphasizes dividend reliability (35%) and fundamentals (30%). High Risk emphasizes sentiment (35%) and catalysts (30%). A ticker's bucket determines which scoring model is applied.",
        "source_name": "Signa Architecture",
    },
    {
        "topic": "SCORING",
        "key_concept": "score_ranges_and_actions",
        "explanation": "Score 75-90 = BUY (strong opportunity). Score 50-74 = HOLD (wait for confirmation). Score below 50 = AVOID (unfavorable risk/reward). Score above 90 = HOLD (overbought ceiling — backtest showed inverted win rates above 72). The 90 ceiling prevents false conviction on overhyped stocks.",
        "source_name": "Signa Backtest Validation",
    },
    {
        "topic": "SCORING",
        "key_concept": "backtest_key_findings",
        "explanation": "6-month backtest (Oct 2024 - Apr 2025, 30 tickers) revealed: (1) RSI 50-65 is the sweet spot — oversold (<30) is NOT better due to falling knife risk. (2) Momentum >5% is a trap with 46.2% win rate vs 58% for 1-3% range. (3) High MACD histogram (>2.0) predicts surges (3.3x avg return). (4) Scores above 72 have inverted win rates. These findings directly shape the scoring rules.",
        "formula": "RSI sweet spot: 50-65; Momentum sweet spot: 1-3%; MACD surge: >2.0; Score ceiling: 90",
        "source_name": "Signa Backtest System",
    },
    {
        "topic": "RISK_MANAGEMENT",
        "key_concept": "gem_conditions",
        "explanation": "GEM (Golden Entry Moment) is the highest-quality signal. ALL 5 conditions must be met simultaneously: (1) Score >= 85, (2) Bullish sentiment with confidence >= 80%, (3) Catalyst within 30 days, (4) Risk/reward ratio >= 3.0x, (5) Zero red flags. GEMs are rare (0-3 per day) and trigger instant Telegram alerts.",
        "formula": "score >= 85 AND sentiment == bullish AND confidence >= 80 AND catalyst_days <= 30 AND risk_reward >= 3.0 AND red_flags == []",
        "source_name": "Signa Signal Engine",
    },
    {
        "topic": "RISK_MANAGEMENT",
        "key_concept": "signal_blockers",
        "explanation": "5 conditions automatically block BUY signals: (1) RSI > 75 (overbought), (2) Hostile macro environment, (3) Volume z-score < -2.0 or avg volume < 50K, (4) Fraud keywords in sentiment, (5) Price below $1.00. Blockers override the score — a blocked ticker always gets AVOID regardless of how high its score might be.",
        "source_name": "Signa Signal Engine",
    },
    {
        "topic": "RISK_MANAGEMENT",
        "key_concept": "kelly_position_sizing",
        "explanation": "Position size is calculated using fractional Kelly Criterion (25% of full Kelly). The formula maps signal score to estimated win rate, then computes optimal allocation. Score 85+ maps to ~65% win rate. Score 75 maps to ~55%. The result is capped at 15% of portfolio. Example: Score 88 with 3.2x risk/reward → recommended ~12% position size.",
        "formula": "kelly_fraction = (win_rate * risk_reward - (1 - win_rate)) / risk_reward; position_pct = kelly_fraction * 0.25; capped at 0.15",
        "example": "Score 88 → win_rate 0.63 → kelly = (0.63*3.2 - 0.37)/3.2 = 0.515 → fractional = 0.515*0.25 = 0.129 → recommend 12.9% position",
        "source_name": "Kelly Criterion (J.L. Kelly Jr., 1956)",
    },
    {
        "topic": "MACRO",
        "key_concept": "macro_environment_classification",
        "explanation": "Macro environment is classified as: FAVORABLE (low rates, low inflation, low VIX), NEUTRAL (mixed signals), or HOSTILE (rising rates + high CPI + elevated VIX). Data sourced from FRED (Federal Reserve Economic Data). Hostile macro is an auto-blocker for BUY signals. VIX thresholds: <15 = calm, 15-20 = normal, 20-25 = elevated, 25-35 = high fear, 35+ = crisis.",
        "formula": "VIX < 15 → 75pts; VIX 15-20 → 65pts; VIX 20-25 → 50pts; VIX 25-35 → 35pts; VIX 35+ → 20pts",
        "source_name": "FRED / Federal Reserve",
    },
    {
        "topic": "SENTIMENT",
        "key_concept": "sentiment_provider_hierarchy",
        "explanation": "Sentiment is analyzed by AI providers in priority order: (1) Grok — has real-time X/Twitter access, most accurate but requires paid credits. (2) Gemini — uses training data knowledge, free tier, good fallback. When all providers fail, sentiment defaults to neutral (score 50, confidence 0). The confidence field distinguishes real sentiment from fallback — confidence 0 means no real data was available.",
        "source_name": "Signa AI Provider System",
    },
    {
        "topic": "CANADIAN_MARKET",
        "key_concept": "tsx_specific_considerations",
        "explanation": "TSX tickers end in .TO suffix. Canadian banks (RY, TD, BNS, BMO, CM, NA) are classified as SAFE_INCOME due to regulated oligopoly and consistent dividends. REITs (-UN.TO suffix) are auto-classified as SAFE_INCOME. TSX operates in Eastern Time (same as Toronto). Canadian macro data from Bank of Canada should supplement US FRED data for TSX tickers.",
        "source_name": "TMX Group / Bank of Canada",
    },
    {
        "topic": "CRYPTO",
        "key_concept": "crypto_handling",
        "explanation": "Crypto tickers end in -USD (e.g., BTC-USD, ETH-USD). Always classified as HIGH_RISK. Trade 24/7 (signals can update on weekends). No fundamental data (P/E, dividends) available — scoring relies more on sentiment and momentum. Pre-filter reserves at least 5 slots for crypto to prevent crowding by higher-volume equities. 18 crypto tickers tracked.",
        "source_name": "Signa Universe",
    },

    # ═══ MACRO: LEADING INDICATORS ═══
    {
        "topic": "MACRO",
        "key_concept": "yield_curve_recession_predictor",
        "explanation": "The 10Y-2Y Treasury spread is the single most reliable recession predictor. When it goes NEGATIVE (inverted), a recession has followed within 12-18 months in 8 of the last 8 times since 1970. BUT the timing nuance is critical: stocks often RALLY during the inversion itself. The real danger comes when the curve UN-INVERTS (goes back positive) after being inverted — this steepening is the actual crash signal, typically 3-9 months before recession hits. ACTIONABLE: Inverted curve = raise caution, tighten stops, reduce position sizes. UN-inverting after inversion = most dangerous macro phase, strongly prefer SAFE_INCOME over HIGH_RISK. Steep positive curve (>150bp) = favorable for growth and HIGH_RISK.",
        "formula": "T10Y2Y < 0 = caution (tighten stops). T10Y2Y turns positive AFTER inversion = danger (prefer SAFE_INCOME). T10Y2Y > 150bp = favorable for growth.",
        "source_name": "Federal Reserve Bank of NY Recession Probability Model",
    },
    {
        "topic": "MACRO",
        "key_concept": "credit_spreads_crash_predictor",
        "explanation": "BBB corporate bond spreads (OAS over Treasuries) measure the market's pricing of corporate default risk. This is the smart money's fear gauge — it moves BEFORE VIX and before stock prices. Normal: 1.0-2.0%. Elevated: 2.0-3.0%. Stress: 3.0-5.0%. Crisis: 5.0%+. ACTIONABLE: When BBB OAS rises above 2.5% AND is rising week-over-week, this is an early warning that credit markets are seizing — reduce HIGH_RISK exposure. When BBB OAS falls below 1.5% after being elevated, this confirms recovery — increase HIGH_RISK confidence. Credit spreads below 1.0% = complacency risk, similar to VIX < 12. NOTE: FRED series BAMLC0A4CBBB has ~1 day lag, always yesterday's value.",
        "formula": "credit_spread < 1.5% = favorable. 1.5-2.5% = neutral. 2.5-3.5% = reduce HIGH_RISK confidence. 3.5%+ = hostile signal.",
        "source_name": "ICE BofA BBB Corporate Bond OAS via FRED",
    },

    # ═══ MACRO: VIX TERM STRUCTURE ═══
    {
        "topic": "MACRO",
        "key_concept": "vix_term_structure_interpretation",
        "explanation": "VIX term structure compares spot VIX to 3-month VIX futures (VIX3M). CONTANGO (spot < futures, ratio < 1.0) is normal — the market expects current calm to persist. BACKWARDATION (spot > futures, ratio > 1.0) means acute fear — the market is more scared NOW than it expects to be later. Ratio > 1.15 = severe stress, historically precedes 5-15% drawdowns within 2 weeks. Ratio < 0.85 = extreme complacency, markets often correct within 30 days. ACTIONABLE: When backwardation ratio > 1.10, reduce HIGH_RISK confidence and tighten stops. When ratio > 1.15, treat as hostile signal — only highest-conviction SAFE_INCOME plays. When contango ratio < 0.85, raise contrarian caution — markets may be too complacent for momentum to sustain.",
        "formula": "ratio = VIX_spot / VIX3M. ratio > 1.15 = hostile. ratio > 1.10 = caution. ratio < 0.85 = complacency warning. 0.85-1.10 = normal.",
        "source_name": "CBOE VIX Term Structure Research",
    },

    # ═══ NEW: MOMENTUM SCIENCE ═══
    {
        "topic": "MOMENTUM_SCIENCE",
        "key_concept": "short_term_momentum_in_large_caps",
        "explanation": "Academic research proves that large-cap high-turnover stocks exhibit SHORT-TERM MOMENTUM with statistically significant premiums. Short-term reversal effects exist ONLY in thinly traded low-turnover micro-cap stocks. For the TSX and US large-cap universe Signa scans, the correct expectation is momentum continuation, not reversal. Stocks with avg daily volume above $1M → expect momentum continuation → BUY into upward momentum. Stocks with avg daily volume below $100K → expect short-term reversal → wait for pullback before entering.",
        "formula": "if avg_daily_dollar_volume > 1000000 AND momentum_5d > 0: momentum_type = CONTINUATION → score boost. if avg_daily_dollar_volume < 100000 AND momentum_5d extreme: momentum_type = REVERSAL → wait for pullback",
        "source_name": "Morningstar - Medhat and Schmeling 2022",
        "source_url": "https://www.morningstar.com/markets/achilles-heel-momentum-strategies",
    },
    {
        "topic": "MOMENTUM_SCIENCE",
        "key_concept": "momentum_crash_avoidance",
        "explanation": "Momentum strategies crash in predictable conditions: PANIC STATES following market declines when market volatility is high. VIX above 30 signals a panic state where momentum reverses violently. Avoid all HIGH_RISK momentum signals when VIX is above 30. SAFE_INCOME dividend signals are less affected and can continue with reduced scores. This is VOLATILITY SCALING — professional momentum managers reduce position sizes when momentum variance is high. Signa implements this by pausing HIGH_RISK signals when VIX exceeds 30.",
        "formula": "if vix > 30: HIGH_RISK signals → HOLD only. if vix > 40: ALL signals → HOLD only. if market_10d_return < -0.05: reduce all scores by 15",
        "source_name": "Morningstar - Momentum Has Its Moments",
        "source_url": "https://www.morningstar.com/markets/achilles-heel-momentum-strategies",
    },
    {
        "topic": "MOMENTUM_SCIENCE",
        "key_concept": "optimal_lookback_windows",
        "explanation": "Different lookback windows serve different purposes. 1 day is noise. 5 days (1 week) is good for catching catalyst-driven moves but has high false positive rate. 20 days (1 month) is the most reliable for Signa's 5-20 day window. 6-12 months is traditional momentum, too slow for Signa. Signa uses 5-day AND 20-day momentum together. Both positive = strong BUY confirmation. 5-day positive and 20-day negative = caution. Both negative = do not enter.",
        "source_name": "JP Morgan Momentum Strategies 2015",
        "source_url": "https://www.cmegroup.com/education/files/jpm-momentum-strategies-2015-04-15-1681565.pdf",
    },

    # ═══ NEW: EVENT-DRIVEN STRATEGY ═══
    {
        "topic": "EVENT_DRIVEN_STRATEGY",
        "key_concept": "event_driven_is_highest_conviction",
        "explanation": "Event-driven trading is the professional hedge fund strategy most directly applicable to Signa. Used by BlackRock, AXA, and most major hedge funds. Profit from corporate events where uncertainty creates mispricing. TIER 1 (score boost +20): earnings within 14 days, dividend ex-date within 7 days, analyst upgrade with price target raise. TIER 2 (score boost +12): share buyback announcement, earnings surprise above 5%, insider buying, index inclusion. TIER 3 (score boost +6): merger/acquisition rumour, sector rotation catalyst, macro catalyst (Fed/CPI). CRITICAL: Event-driven signals must EXIT before or immediately after the event resolves.",
        "formula": "urgency_score = 100 - (days_to_event * 3), capped at 95 minimum 0. Tier 1 event + urgency_score > 60 = GEM candidate",
        "source_name": "AXA IM Prime Hedge Fund Strategy Overview",
        "source_url": "https://www.axa-im.com/document/7328/view",
    },
    {
        "topic": "EVENT_DRIVEN_STRATEGY",
        "key_concept": "post_earnings_announcement_drift",
        "explanation": "Post-Earnings Announcement Drift (PEAD) is one of the most documented market anomalies. After an earnings SURPRISE where actual beats estimate, the stock continues to drift in the direction of the surprise for days to weeks. Strongest in first 1-3 days, continues days 4-10, mostly priced in by day 11-20. Signa generates a POST-EARNINGS BUY signal when ALL of these are true: EPS surprise above 3%, earnings released 0-3 days ago, price has not already surged more than 10%, volume is elevated, RSI is not overbought (below 65). IMPORTANT: PEAD and PRE_EARNINGS are mutually exclusive. If earnings happened within 3 days, use PEAD only.",
        "formula": "pead_signal requires: eps_surprise > 0.03 AND days_since_earnings <= 3 AND price_change_since_earnings < 0.10 AND volume_ratio > 1.3 AND rsi < 65 → hold 5-10 days",
        "example": "SHOP.TO reports Q2 earnings beating estimates by 8%. Price opens +4%. Signa detects PEAD: score boost, signal BUY with 5-10 day hold. Day 3 stock is +7% total. Day 10 stock is +11%.",
        "source_name": "Quantpedia - Momentum Factor Effect in Stocks",
        "source_url": "https://quantpedia.com/strategies/momentum-factor-effect-in-stocks",
    },

    # ═══ NEW: MARKET REGIME ═══
    {
        "topic": "MARKET_REGIME",
        "key_concept": "market_regime_detection",
        "explanation": "Three market regimes define how signals are generated: TRENDING (normal) when S&P 500 is above SMA50 and VIX below 20 — full signal generation, normal Kelly sizing. VOLATILE (caution) when VIX 20-30 or S&P between SMA50 and SMA200 — HIGH_RISK score threshold raised to 80, Kelly sizing reduced 50%. CRISIS (defensive) when VIX above 30 or S&P below SMA200 — HIGH_RISK signals paused entirely, SAFE_INCOME dividend plays only, Kelly capped at 5%. Regime is checked ONCE per day at morning scan.",
        "formula": "if vix > 30 or spy_vs_sma200 < -2: regime = CRISIS. elif vix > 20 or spy_vs_sma50 < -1: regime = VOLATILE. else: regime = TRENDING",
        "source_name": "BlackRock Systematic Alpha Research",
        "source_url": "https://www.blackrock.com/us/financial-professionals/insights/data-driven-investing",
    },
    {
        "topic": "MARKET_REGIME",
        "key_concept": "dispersion_as_opportunity",
        "explanation": "Today's post-COVID market has higher dispersion — companies differ more in their ability to navigate challenges. Higher dispersion means more opportunities for signal-based selection. When sector dispersion is high (spread between best and worst stocks >15% over 20 days), increase confidence in sector-specific signals. When all stocks move together with low dispersion, reduce confidence in individual signals.",
        "source_name": "BlackRock Market Neutral Investing",
        "source_url": "https://www.blackrock.com/us/financial-professionals/insights/market-neutral-investing",
    },

    # ═══ MARKET REGIME: RECOVERY ═══
    {
        "topic": "MARKET_REGIME",
        "key_concept": "recovery_regime_opportunity",
        "explanation": "RECOVERY is the fourth market regime, distinct from TRENDING. It occurs when VIX is falling from crisis levels (20-30 range), SPY has reclaimed its 50-day SMA, and VIX was above 30 within the last 30 days. Historically, RECOVERY produces the highest risk-adjusted returns of any regime (DeStefano, 2004). Momentum strategies work exceptionally well because the bear-to-bull reversal is OVER and a new trend is forming. Value stocks that were crushed in the prior crisis also outperform. ACTIONABLE: In RECOVERY regime, increase HIGH_RISK confidence. Favor stocks that fell the most in the prior crisis and are now showing momentum recovery — beaten-down + fresh momentum confirmation = highest alpha setup. Kelly sizing can be normal or slightly aggressive. SAFE_INCOME continues as normal.",
        "formula": "RECOVERY = VIX between 20-30 AND falling AND SPY > SMA50 AND recent crisis (VIX was >30 in last 30 days). HIGH_RISK score boost +10%.",
        "source_name": "DeStefano 2004 - Stock Returns and the Business Cycle",
    },

    # ═══ NEW: CANADA TAX RULES ═══
    {
        "topic": "CANADA_TAX_RULES",
        "key_concept": "canada_account_type_strategy",
        "explanation": "CRITICAL FOR CANADIAN INVESTORS. TFSA: ideal for long holds (30+ days), dividend income, ETFs. Risk: CRA may classify frequent short-term trading as business income, making all profits 100% taxable. Safe range: holds 30+ days, <20 trades/year. Use for SAFE_INCOME signals only. RRSP: ideal for active trading — CRA explicitly exempts RRSP from business income tax on qualified investments (Income Tax Act Folio 10). Use for HIGH_RISK signals. TAXABLE: capital gains at 50% inclusion rate. Superficial loss rule: cannot claim capital loss if you rebuy within 30 days. SIGNA RECOMMENDATION: SAFE_INCOME → TFSA, HIGH_RISK → RRSP, Taxable as fallback. DISCLAIMER: This is general education only, not tax advice.",
        "source_name": "Questrade TFSA Day Trading Rules",
        "source_url": "https://www.questrade.com/learning/tfsa-day-trading-cra-rules",
    },
    {
        "topic": "CANADA_TAX_RULES",
        "key_concept": "cra_day_trading_five_factors",
        "explanation": "CRA evaluates day trading using five factors: (1) Frequency of transactions, (2) Duration of holdings — same-day holds are highest risk, Signa's 5-20 day window is gray area, (3) Intention to resell for profit — all Signa signals have explicit exit plans, (4) Skill/knowledge level — using AI analysis signals professional activity, (5) Time spent on activity. Risk mitigation: execute HIGH_RISK in RRSP, keep TFSA for buy-and-hold, limit TFSA trades to <20/year, document investment intent. SUPERFICIAL LOSS RULE: selling at a loss and rebuying within 30 days denies the capital loss.",
        "source_name": "Fidelity Canada Day Trading Article",
        "source_url": "https://www.fidelity.ca/en/insights/articles/day-trading-in-canada/",
    },
    {
        "topic": "CANADA_TAX_RULES",
        "key_concept": "capital_gains_vs_business_income_canada",
        "explanation": "The most important Canadian tax distinction. CAPITAL GAINS (preferred): 50% inclusion rate — only half the profit is taxable. $10,000 gain = $5,000 taxable income. BUSINESS INCOME (avoid): 100% inclusion — full amount taxable at marginal rate up to ~53%. $10,000 gain = $10,000 taxable. Tax difference on $10,000 in the 50% bracket: capital gains = ~$2,500 tax, business income = ~$5,000 tax. Signa's 5-20 day signals are most safely treated as short-term investing, not day trading.",
        "source_name": "TurboTax Canada Capital Gains Day Trading",
        "source_url": "https://turbotax.intuit.ca/tips/how-to-calculate-capital-gains-when-day-trading-in-canada-6251",
    },

    # ═══ NEW: INSTITUTIONAL EDGE ═══
    {
        "topic": "INSTITUTIONAL_EDGE",
        "key_concept": "blackrock_systematic_five_principles",
        "explanation": "Key principles from BlackRock Systematic's 40-year track record that Signa embeds: (1) Multiple independent signals — no single indicator is reliable alone, Signa's 5-layer stack follows this. (2) Daily forecasting for nimbleness — 3x daily scans. (3) Scientific testing reduces behavioral bias — Claude applies rules consistently without emotional override. (4) Data quality over quantity — Grok sentiment has edge only when ticker has >500 monthly mentions AND sentiment has shifted in last 48h. (5) Volatility-adjusted position sizing via Kelly Criterion.",
        "source_name": "BlackRock Alpha Reimagined",
        "source_url": "https://www.blackrock.com/institutions/en-global/institutional-insights/thought-leadership/alpha-reimagined",
    },
    {
        "topic": "INSTITUTIONAL_EDGE",
        "key_concept": "factor_rotation_by_regime",
        "explanation": "Professional quant funds rotate factors by market regime. MOMENTUM works in trending markets with rising earnings — fails in high volatility (VIX>30). VALUE (low P/E) works in rate-rising environments and recovery phases. QUALITY (high ROE, low debt) works in late cycle — always provides protection. CARRY (dividends) works in stable/falling rate environments. SIGNA APPLICATION: TRENDING regime → weight momentum heavily. VOLATILE → shift toward quality and carry. CRISIS → dividends/carry only.",
        "source_name": "AXA IM Prime and JP Morgan Momentum Research",
        "source_url": "https://www.cmegroup.com/education/files/jpm-momentum-strategies-2015-04-15-1681565.pdf",
    },
    {
        "topic": "INSTITUTIONAL_EDGE",
        "key_concept": "grok_sentiment_calibration",
        "explanation": "Grok X/Twitter sentiment is most valuable when: ticker has >500 mentions in 48h, sentiment has CHANGED significantly, breaking news detected, notable accounts (analysts/insiders) talking, sentiment consistent for 2+ days. Low-value conditions: <100 mentions (quiet company), sentiment high for >7 days (momentum exhaustion), only retail accounts, extreme scores (>90 or <10). CONTRARIAN: when Grok score >85 (extreme bullish) reduce confidence by 10 points — crowd already positioned. When <15 (extreme bearish) AND fundamentals solid, increase confidence by 10 — fear overdone. If mention_count < 100: weight sentiment at 5% only, redistribute to technical score.",
        "source_name": "BlackRock Systematic and Buffett Research",
        "source_url": "https://www.blackrock.com/us/financial-professionals/insights/data-driven-investing",
    },

    # ═══ NEW: CONTRARIAN / SUPPLY-DEMAND KNOWLEDGE ═══
    {
        "topic": "SECTOR_ANALYSIS",
        "key_concept": "supply_deficit_asymmetry",
        "explanation": "When a commodity sector shows: (a) demand growing steadily or stable, (b) supply declining due to years of underinvestment in new capacity, (c) spot price at or below marginal production cost, and (d) end-buyer is price-inelastic (utilities buying uranium, airlines buying fuel, manufacturers buying chemicals) — this creates an asymmetric setup where downside is limited by production economics but upside is uncapped. The key insight: producers MUST be paid above production cost long-term or they shut down, which further reduces supply and forces price higher. This is a self-correcting mechanism that creates a natural price floor.",
        "formula": "IF demand_stable_or_growing AND supply_declining AND spot_price < 1.3 * production_cost AND end_buyer_price_inelastic THEN asymmetric_opportunity = TRUE",
        "example": "Uranium in 2021-2023: spot price ~$50/lb, production cost ~$60/lb for most mines. Utilities needed uranium regardless of price. Only 2 options: price rises above production cost, or lights go off. Price rose to $100+ by 2024.",
        "source_name": "Commodity Supply-Demand Economics",
        "source_url": "https://www.investopedia.com/terms/s/supply.asp",
    },
    {
        "topic": "SECTOR_ANALYSIS",
        "key_concept": "contrarian_sentiment_in_commodities",
        "explanation": "In commodity sectors, extreme negative sentiment often signals opportunity rather than danger — the opposite of what standard sentiment scoring suggests. When capital has fled a sector, analyst coverage has dropped, and remaining investors are demoralized, the contrarian signal is bullish IF fundamental supply-demand dynamics are improving. The highest-return commodity investments in history were made when sentiment was maximally negative. Standard sentiment scoring (negative = sell) is WRONG for commodity sectors with supply deficits. Signa should detect when a whole sector is hated but fundamentals are improving, and flip the sentiment interpretation.",
        "formula": "IF sector_sentiment < 25 AND sector_supply_deficit EXISTS AND no_fraud_flags THEN contrarian_bullish = TRUE → flip sentiment penalty to bonus",
        "source_name": "Contrarian Value Investing Research",
        "source_url": "https://www.investopedia.com/terms/c/contrarian.asp",
    },
    {
        "topic": "SECTOR_ANALYSIS",
        "key_concept": "replacement_cost_valuation",
        "explanation": "For capital-intensive businesses (offshore drillers, miners, chemical plants, refineries), replacement cost is a critical valuation floor. When a company's market cap falls below 50% of what it would cost to build its assets from scratch, the stock is deeply mispriced. At that point, it's cheaper to buy the company than to build new capacity — which attracts acquirers and creates a natural price floor. Key nuance: 'replacement cost' must use current new-build prices, not historical book value. A drilling rig that cost $200M to build in 2014 might sell for $40M in a downturn, but a new-build in 2026 costs $250M. The company owning the $40M rig has $250M of replacement value.",
        "formula": "IF market_cap < 0.5 * sum(replacement_cost_of_assets) THEN deep_value_flag = TRUE → score_boost +12",
        "example": "Offshore driller acquires 5 jack-up rigs for $287M ($57M each). New-build cost is $250M per rig. Market values the fleet at fraction of replacement. Acquirer gets $1.25B of assets for $287M.",
        "source_name": "Replacement Cost Analysis",
        "source_url": "https://www.investopedia.com/terms/r/replacementcost.asp",
    },
    {
        "topic": "RISK_MANAGEMENT",
        "key_concept": "bubble_detection_framework",
        "explanation": "Bubble conditions exist when: (1) sector average P/E exceeds 50x with majority of companies unprofitable, (2) consensus is overwhelmingly bullish with sentiment above 85, (3) retail participation is surging (high mention counts from non-institutional accounts), (4) new companies in the sector are being valued on 'total addressable market' rather than actual revenue. When all 4 conditions are present, apply a -10 point score penalty to all signals in that sector. This is NOT a hard blocker — some companies in a bubbly sector have real earnings. It's a caution flag that raises the conviction bar. As of 2026, AI/tech meets several of these criteria.",
        "formula": "IF sector_avg_pe > 50 AND pct_unprofitable > 0.5 AND sector_sentiment > 85 AND retail_surge THEN bubble_caution = TRUE → score_penalty -10",
        "source_name": "Market Bubble Research (Kindleberger, Shiller)",
        "source_url": "https://www.investopedia.com/terms/b/bubble.asp",
    },
    # ═══ NEW: RESEARCH-BACKED KNOWLEDGE ENRICHMENT ═══
    {
        "topic": "MOMENTUM_SCIENCE",
        "key_concept": "momentum_crash_specific_conditions",
        "explanation": "Momentum crashes follow a specific pattern documented by Barroso and Santa-Clara (2015): (1) A sharp market decline (SPY drops >10% in <30 days), (2) VIX spikes above 30, (3) Then the BEAR-TO-BULL REVERSAL happens — the market bounces violently. In this reversal, last year's LOSERS outperform last year's WINNERS by 20-40% in a single month. This is when momentum strategies suffer catastrophic losses. The key: momentum works in trending markets, fails in reversals from extremes. ACTIONABLE: After a >10% market decline followed by a >5% bounce within 5 days, PAUSE all momentum-based HIGH_RISK signals for 10 trading days. Let the reversal play out. Resume when VIX falls below 25 and stays there for 5+ consecutive days.",
        "formula": "IF spy_30d_return < -10% AND spy_5d_return > 5% THEN momentum_reversal_risk = TRUE → pause HIGH_RISK momentum for 10 days. Resume when VIX < 25 for 5+ days.",
        "source_name": "Barroso and Santa-Clara 2015 - Momentum Has Its Moments",
    },
    {
        "topic": "RISK_MANAGEMENT",
        "key_concept": "crisis_correlation_convergence",
        "explanation": "During market crises, correlations between all risky assets converge toward 1.0 (Longin and Solnik, 2001). This means diversification FAILS exactly when you need it most. Stocks, corporate bonds, commodities, and crypto all fall together — holding 10 different HIGH_RISK positions provides almost zero diversification benefit in a crisis. Only US Treasuries, gold, and cash provide real diversification during crises. ACTIONABLE: When regime is CRISIS or VIX > 35, do NOT assume that holding multiple different HIGH_RISK signals provides safety through diversification. Reduce total HIGH_RISK exposure to max 2 positions regardless of how many BUY signals fire. Concentrate remaining exposure in SAFE_INCOME with proven dividends. When VIX > 40, strongly prefer cash or equivalent.",
        "formula": "IF regime == CRISIS: max_high_risk_positions = 2. IF vix > 40: max_high_risk_positions = 0, SAFE_INCOME only.",
        "source_name": "Longin and Solnik 2001 - Extreme Correlation of International Equity Markets",
    },
    {
        "topic": "SCORING",
        "key_concept": "factor_independence_warning",
        "explanation": "Not all scoring factors are independent. RSI and momentum are correlated (~0.6). MACD and momentum are highly correlated (~0.7). Sentiment and price momentum are correlated during trends (~0.5). This means a stock scoring high on RSI, MACD, AND momentum is not 3x confirmed — it is roughly 1.5x confirmed because the factors overlap. Truly INDEPENDENT factor pairs that provide unique information: (1) sentiment vs technicals (correlation ~0.2 in normal markets), (2) fundamentals vs momentum (correlation ~0.1), (3) macro vs stock-specific (correlation ~0.0), (4) catalyst timing vs everything else. ACTIONABLE: When evaluating a BUY signal, check if the confirming factors are actually independent. A signal confirmed by sentiment + fundamentals + catalyst is STRONGER than one confirmed by RSI + MACD + momentum, even if both have similar composite scores.",
        "formula": "Independent pairs: sentiment-technicals, fundamentals-momentum, macro-stock, catalyst-everything. Redundant pairs: RSI-momentum, MACD-momentum, RSI-MACD.",
        "source_name": "Fama-French Factor Research / Principal Component Analysis",
    },
    {
        "topic": "EVENT_DRIVEN_STRATEGY",
        "key_concept": "pead_decay_curve_and_optimal_hold",
        "explanation": "Research-backed PEAD timing from Bernard and Thomas (1989), updated by Livnat and Mendenhall (2006): Day 0-1 after earnings surprise: 40% of total drift occurs (largest single move). Day 2-5: another 30% of drift. Day 6-10: another 20% of drift. Day 11-20: remaining 10%, mostly noise. Day 20+: drift is fully priced in. OPTIMAL ENTRY: Day 0-1 (same day or next day after earnings). OPTIMAL EXIT: Day 7-10 (capture 90% of drift, avoid the noisy tail). Holding beyond day 10 adds risk without proportional reward. EPS surprise magnitude matters: >10% surprise = strongest drift, hold full 10 days. 5-10% = moderate drift, exit by day 7. 3-5% = weak drift, exit by day 5. <3% = not tradeable as PEAD.",
        "formula": "PEAD entry: day 0-1. Exit: day 7-10. Surprise > 10% = hold full 10 days. Surprise 5-10% = exit by day 7. Surprise 3-5% = exit by day 5.",
        "source_name": "Bernard and Thomas 1989, updated by Livnat and Mendenhall 2006",
    },
    {
        "topic": "RISK_MANAGEMENT",
        "key_concept": "small_sample_fat_tail_warning",
        "explanation": "Financial returns have fat-tailed distributions (Taleb, 2001). This means: (1) Rare extreme events happen far more often than a normal distribution predicts. (2) Small sample backtests (< 30 trades) CANNOT reliably estimate tail risk. (3) A strategy that 'worked' on 5-10 trades may have simply not yet encountered the tail event that destroys it. An 80% win rate on N=5 has a 95% confidence interval of [28%, 99%] — it tells you almost nothing. ACTIONABLE: When pattern_stats show fewer than 30 observations for a pattern, treat the win rate estimate as unreliable. Do NOT increase position sizes based on high win rates from small samples. Require at least 30 observations before treating a pattern as tentative, 100+ before adjusting Kelly parameters. The brain's current graduation threshold of 5 observations is fine for hypotheses but insufficient for confident knowledge.",
        "formula": "observations < 30 = hypothesis only, keep kelly conservative. 30-100 = tentative, can inform but not override. 100+ = reliable enough for sizing adjustments.",
        "source_name": "Taleb - Fooled by Randomness / Statistical Learning Theory",
    },
    {
        "topic": "RISK_MANAGEMENT",
        "key_concept": "put_call_ratio_contrarian",
        "explanation": "The put/call volume ratio (available from options flow data) is a powerful contrarian indicator at extremes. Extreme high put/call (>1.2) = excessive hedging/fear = contrarian bullish signal — the crowd is already positioned for decline, creating a setup for a rally. Extreme low put/call (<0.5) = excessive complacency = contrarian bearish — the crowd has no hedges, vulnerable to any shock. Normal range (0.7-1.0) = no signal, ignore. ACTIONABLE: Most useful when combined with other contrarian indicators: oversold RSI + high put/call (>1.2) + VIX spike = strong contrarian BUY setup. Overbought RSI + low put/call (<0.5) + VIX complacency = caution flag on BUY signals.",
        "formula": "put_call > 1.2 = contrarian bullish. put_call < 0.5 = contrarian bearish. 0.7-1.0 = neutral, no signal.",
        "source_name": "CBOE Put/Call Ratio Research",
    },

    {
        "topic": "RISK_MANAGEMENT",
        "key_concept": "volatility_vs_permanent_loss",
        "explanation": "Standard finance defines risk as volatility (standard deviation of returns). Deep-value investors reject this entirely. True risk is permanent capital loss — buying something that goes to zero. A stock trading at 25% of intrinsic value with high daily volatility is LESS risky than a fully-valued stock with low volatility, because the undervalued stock has massive margin of safety. Signa should not automatically penalize signals for volatile price action if the underlying asset is deeply undervalued with strong fundamentals. Volatility in a deeply discounted asset is opportunity, not risk. Practical application: when a signal has score 70+ AND price is below 50% of intrinsic/replacement value, do NOT apply volatility-based score penalties.",
        "source_name": "Benjamin Graham / Seth Klarman - Margin of Safety",
        "source_url": "https://www.investopedia.com/terms/m/marginofsafety.asp",
    },
]


def seed():
    """Insert all rules and knowledge into Supabase."""
    client = get_client()

    # Seed investment_rules
    logger.info("Seeding investment_rules...")
    for rule in INVESTMENT_RULES:
        rule["is_active"] = True
        try:
            client.table("investment_rules").upsert(rule, on_conflict="name").execute()
        except Exception as e:
            logger.error(f"Failed to seed rule {rule['name']}: {e}")

    logger.info(f"Seeded {len(INVESTMENT_RULES)} investment rules")

    # Seed signal_knowledge
    logger.info("Seeding signal_knowledge...")
    for knowledge in SIGNAL_KNOWLEDGE:
        knowledge["is_active"] = True
        try:
            client.table("signal_knowledge").upsert(knowledge, on_conflict="key_concept").execute()
        except Exception as e:
            logger.error(f"Failed to seed knowledge {knowledge['key_concept']}: {e}")

    logger.info(f"Seeded {len(SIGNAL_KNOWLEDGE)} signal knowledge entries")


if __name__ == "__main__":
    seed()
